"""
WhisperX Subtitle Generator - GUI
----------------------------------
Batch transcribe + translate subtitles using your NVIDIA GPU.
Requires: pip install whisperx transformers sentencepiece sacremoses torch
"""

import tkinter as tk
from tkinter import ttk, filedialog, scrolledtext
import threading
import os
import sys
import queue
from pathlib import Path

# Suppress Windows "DLL load failed" popup dialogs (e.g. from torchcodec)
try:
    import ctypes
    ctypes.windll.kernel32.SetErrorMode(0x8003)  # SEM_FAILCRITICALERRORS | SEM_NOOPENFILEERRORBOX
except Exception:
    pass

# ─── Color palette ───────────────────────────────────────────────────────────
BG          = "#0f0f0f"
BG_PANEL    = "#181818"
BG_INPUT    = "#1e1e1e"
BG_HOVER    = "#252525"
ACCENT      = "#1db954"
ACCENT_DIM  = "#158a3e"
TEXT        = "#e8e8e8"
TEXT_DIM    = "#888888"
TEXT_MUTED  = "#555555"
BORDER      = "#2a2a2a"
WARN        = "#e8a020"
ERROR_COL   = "#e84040"
SUCCESS_COL = "#1db954"

VIDEO_EXTENSIONS = {'.mkv', '.mp4', '.avi', '.m2ts', '.ts', '.mov', '.wmv'}

log_queue = queue.Queue()

# Tag written to first line of every SRT we generate
OUR_TAG = "; generated by whisperx-subgen"

# ─── Library database ─────────────────────────────────────────────────────────
class LibraryDB:
    """Persistent JSON store tracking subtitle status per video file."""

    def __init__(self, path: Path):
        self.path = path
        self.data = {}
        self._load()

    def _load(self):
        if self.path.exists():
            try:
                import json
                self.data = json.loads(self.path.read_text(encoding="utf-8"))
            except Exception:
                self.data = {}

    def save(self):
        import json
        self.path.write_text(json.dumps(self.data, indent=2), encoding="utf-8")

    def update(self, video: Path, status: str, our_srt: bool, srt_path: str = "",
               fingerprint: str = ""):
        import time
        self.data[str(video)] = {
            "status":      status,
            "our_srt":     our_srt,
            "srt_path":    srt_path,
            "fingerprint": fingerprint,
            "scanned_at":  time.time(),
        }

    def get(self, video: Path) -> dict:
        return self.data.get(str(video), {})


def file_fingerprint(p: Path) -> str:
    """Fast fingerprint using size + mtime — no file reading needed."""
    try:
        st = p.stat()
        return f"{st.st_size}:{st.st_mtime:.0f}"
    except Exception:
        return ""


def is_our_srt(srt_path: Path) -> bool:
    """Check if an SRT file was generated by this app."""
    try:
        for enc in ("utf-8-sig", "utf-8", "latin-1"):
            try:
                first = srt_path.read_text(encoding=enc, errors="ignore")[:200]
                if OUR_TAG in first:
                    return True
                break
            except Exception:
                continue
        return False
    except Exception:
        return False


def scan_video_status(video: Path, lang: str,
                      cached: dict = None) -> tuple:
    """
    Returns (status, our_srt, srt_path, fingerprint).

    Checks all known SRT variants explicitly — does not rely solely on
    iterdir so it works reliably on NAS/network drives.
    """
    fp = file_fingerprint(video)
    stem = video.stem
    base = str(video.with_suffix(""))  # strip video extension

    # Explicitly check all common language variants — catches .en.srt, .nb.srt etc.
    COMMON_LANGS = ["en", "no", "nb", "sv", "da", "de", "fr", "es", "fi", "nl", "it"]
    explicit = [Path(f"{base}.{l}.srt") for l in COMMON_LANGS]
    explicit += [Path(f"{base}.srt")]
    if lang not in COMMON_LANGS:
        explicit.insert(0, Path(f"{base}.{lang}.srt"))

    # Also scan directory for any other variants we may have missed
    try:
        dir_srts = [f for f in video.parent.iterdir()
                    if f.suffix.lower() == ".srt"
                    and f.stem.lower().startswith(stem.lower())]
    except Exception:
        dir_srts = []

    # Deduplicate, explicit first
    seen = set()
    candidates = []
    for s in explicit + dir_srts:
        if s not in seen:
            seen.add(s)
            candidates.append(s)

    for srt in candidates:
        if srt.exists():
            ours = is_our_srt(srt)
            if ours:
                if cached and cached.get("fingerprint") and cached["fingerprint"] != fp:
                    return "CHANGED", True, str(srt), fp
                return "DONE", True, str(srt), fp
            else:
                return "EXTERNAL", False, str(srt), fp

    # No subtitle found — use cache only for NEW vs UNPROCESSED distinction
    if cached and cached.get("scanned_at"):
        return "UNPROCESSED", False, "", fp
    return "NEW", False, "", fp


# ─── Styled button ────────────────────────────────────────────────────────────
class FlatButton(tk.Button):
    def __init__(self, parent, text, command=None, accent=False, width=None, height=None, **kw):
        bg = ACCENT if accent else BG_INPUT
        fg = "#000000" if accent else TEXT
        abg = ACCENT_DIM if accent else BG_HOVER
        super().__init__(
            parent, text=text, command=command,
            bg=bg, fg=fg, activebackground=abg, activeforeground=fg,
            relief="flat", borderwidth=0,
            font=("Consolas", 10, "bold"),
            cursor="hand2", padx=10, pady=4,
            **kw
        )
        self._accent = accent
        self._bg = bg
        self._abg = abg
        self.bind("<Enter>", lambda e: self.configure(bg=abg))
        self.bind("<Leave>", lambda e: self.configure(bg=bg))

    def configure_text(self, text):
        self.configure(text=text)


# ─── Section label ────────────────────────────────────────────────────────────
def section_label(parent, text):
    f = tk.Frame(parent, bg=BG_PANEL)
    tk.Label(f, text=text.upper(), font=("Consolas", 9, "bold"),
             fg=TEXT_MUTED, bg=BG_PANEL).pack(side="left")
    tk.Frame(f, bg=BORDER, height=1).pack(side="left", fill="x", expand=True, padx=(8, 0), pady=6)
    return f


def styled_entry(parent, textvariable, width=30):
    e = tk.Entry(parent, textvariable=textvariable, width=width,
                 bg=BG_INPUT, fg=TEXT, insertbackground=TEXT,
                 relief="flat", font=("Consolas", 10),
                 highlightthickness=1, highlightbackground=BORDER,
                 highlightcolor=ACCENT)
    return e


def styled_combo(parent, values, textvariable, width=28):
    style = ttk.Style()
    style.theme_use("clam")
    style.configure("Dark.TCombobox",
                     fieldbackground=BG_INPUT, background=BG_INPUT,
                     foreground=TEXT, arrowcolor=TEXT_DIM,
                     bordercolor=BORDER, lightcolor=BORDER, darkcolor=BORDER,
                     selectbackground=BG_INPUT, selectforeground=TEXT)
    style.map("Dark.TCombobox",
              fieldbackground=[("readonly", BG_INPUT)],
              foreground=[("readonly", TEXT)],
              background=[("active", BG_HOVER)])
    c = ttk.Combobox(parent, values=values, textvariable=textvariable,
                     width=width, style="Dark.TCombobox",
                     state="readonly", font=("Consolas", 10))
    return c


# ─── Main App ─────────────────────────────────────────────────────────────────
class SubtitleApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("WhisperX Subtitle Generator")
        self.configure(bg=BG)
        self.resizable(True, True)
        self.geometry("820x980")
        self.minsize(700, 800)

        # Variables
        self.folder_var       = tk.StringVar(value="")
        self.queue_folders    = []
        self.model_var        = tk.StringVar(value="medium")
        self.compute_var      = tk.StringVar(value="float16")
        self.lang_var         = tk.StringVar(value="auto-detect")
        self.target_var       = tk.StringVar(value="English (en)")
        self.trans_engine_var = tk.StringVar(value="Argos (local, offline)")
        self.skip_var         = tk.BooleanVar(value=True)
        self.skip_no_var      = tk.BooleanVar(value=True)
        self.keep_orig_var    = tk.BooleanVar(value=True)
        self.dry_run_var      = tk.BooleanVar(value=False)
        self.delete_en_var    = tk.BooleanVar(value=False)
        self.delete_no_var    = tk.BooleanVar(value=False)
        self.batch_size_var   = tk.StringVar(value="4")
        self.scan_lang_var    = tk.StringVar(value="no")

        # Library state
        self.script_dir   = Path(os.path.dirname(os.path.abspath(__file__)))
        self.library_db   = LibraryDB(self.script_dir / "library.json")
        self.root_folders = self.library_db.data.get("__roots__", [])
        self.lib_entries  = []
        self.lib_mode     = tk.StringVar(value="library")  # kept for compat

        self.video_files  = []
        self.job_list     = []   # list of {"path": Path, "status": "pending"|"running"|"done"|"error", "iid": str}
        self.is_running   = False

        self._build_ui()
        self._poll_log()
        self.protocol("WM_DELETE_WINDOW", self._quit)
        # Load cached library data on startup — no NAS access
        if self.root_folders:
            self.after(100, self._lib_load_from_cache)

    # ── UI construction ───────────────────────────────────────────────────────
    def _build_ui(self):
        # Header
        hdr = tk.Frame(self, bg=BG, pady=16)
        hdr.pack(fill="x", padx=24)
        tk.Label(hdr, text="◈ WhisperX", font=("Consolas", 18, "bold"),
                 fg=ACCENT, bg=BG).pack(side="left")
        tk.Label(hdr, text=" Subtitle Generator", font=("Consolas", 18),
                 fg=TEXT, bg=BG).pack(side="left")
        self.gpu_badge = tk.Label(hdr, text="  checking GPU…  ",
                                  font=("Consolas", 9), fg=TEXT_DIM,
                                  bg=BG_INPUT, relief="flat", padx=6, pady=2)
        self.gpu_badge.pack(side="right")
        self.after(200, self._check_gpu)

        # ── Bottom bar — packed BEFORE outer so it's always visible ──────────
        bar = tk.Frame(self, bg=BG, pady=12)
        bar.pack(fill="x", padx=24, side="bottom")

        self.status_label = tk.Label(bar, text="Ready.", font=("Consolas", 9),
                                     fg=TEXT_MUTED, bg=BG, anchor="w")
        self.status_label.pack(side="left", fill="x", expand=True)

        self.run_btn = FlatButton(bar, "▶  Start Processing",
                                  command=self._start, accent=True)
        self.run_btn.pack(side="right")

        FlatButton(bar, "Clear Log", command=self._clear_log).pack(side="right", padx=(0, 8))
        FlatButton(bar, "Quit", command=self._quit).pack(side="right", padx=(0, 8))

        # Main scroll area
        outer = tk.Frame(self, bg=BG)
        outer.pack(fill="both", expand=True, padx=24, pady=(0, 8))

        # ── Queue card ────────────────────────────────────────────────────────
        top_card = tk.Frame(outer, bg=BG_PANEL, padx=16, pady=14)
        top_card.pack(fill="both", expand=True, pady=(0, 8))

        section_label(top_card, "Processing Queue").pack(fill="x", pady=(0, 8))

        # Library button row
        lib_btn_row = tk.Frame(top_card, bg=BG_PANEL)
        lib_btn_row.pack(fill="x", pady=(0, 6))
        FlatButton(lib_btn_row, "📂  Open Library Manager",
                   command=self._open_library).pack(side="left")
        tk.Label(lib_btn_row, text="Manual:", font=("Consolas", 9), fg=TEXT_DIM,
                 bg=BG_PANEL).pack(side="left", padx=(16, 6))
        self.add_entry = styled_entry(lib_btn_row, self.folder_var, width=32)
        self.add_entry.pack(side="left", fill="x", expand=True, padx=(0, 8))
        FlatButton(lib_btn_row, "Browse", command=self._browse).pack(side="left")
        FlatButton(lib_btn_row, "Add", command=self._add_to_queue).pack(side="left", padx=(6, 0))

        # Job list treeview
        jlist_frame = tk.Frame(top_card, bg=BG_PANEL)
        jlist_frame.pack(fill="both", expand=True, pady=(0, 6))

        style = ttk.Style()
        style.configure("Jobs.Treeview",
                        background=BG_INPUT, foreground=TEXT,
                        fieldbackground=BG_INPUT, rowheight=20,
                        font=("Consolas", 9))
        style.configure("Jobs.Treeview.Heading",
                        background=BG_PANEL, foreground=TEXT_DIM,
                        font=("Consolas", 9, "bold"), relief="flat")
        style.map("Jobs.Treeview",
                  background=[("selected", "#1a2a1a")],
                  foreground=[("selected", ACCENT)])

        jlist_vsb = tk.Scrollbar(jlist_frame, orient="vertical",
                                  bg=BG_INPUT, troughcolor=BG_INPUT, width=10)
        self.job_tree = ttk.Treeview(jlist_frame, style="Jobs.Treeview",
                                      columns=("status", "name"),
                                      show="headings", height=12,
                                      yscrollcommand=jlist_vsb.set,
                                      selectmode="extended")
        self.job_tree.heading("status", text="")
        self.job_tree.heading("name",   text="FILE")
        self.job_tree.column("status", width=26,  stretch=False, anchor="center")
        self.job_tree.column("name",   width=600, stretch=True)
        self.job_tree.tag_configure("pending",    foreground=TEXT_DIM)
        self.job_tree.tag_configure("running",    foreground=ACCENT)
        self.job_tree.tag_configure("done",       foreground=SUCCESS_COL)
        self.job_tree.tag_configure("error",      foreground=ERROR_COL)
        jlist_vsb.config(command=self.job_tree.yview)
        self.job_tree.pack(side="left", fill="both", expand=True)
        jlist_vsb.pack(side="right", fill="y")

        # Job list controls
        jctrl_row = tk.Frame(top_card, bg=BG_PANEL)
        jctrl_row.pack(fill="x")
        FlatButton(jctrl_row, "✕ Remove",    command=self._job_remove).pack(side="left", padx=(0,6))
        FlatButton(jctrl_row, "Clear Done",  command=self._job_clear_done).pack(side="left", padx=(0,6))
        FlatButton(jctrl_row, "Clear All",   command=self._job_clear_all).pack(side="left", padx=(0,6))
        self.file_label = tk.Label(jctrl_row, text="Queue is empty.",
                                   font=("Consolas", 9), fg=TEXT_MUTED, bg=BG_PANEL)
        self.file_label.pack(side="left", padx=(12, 0))
        FlatButton(jctrl_row, "Scan Folders", command=self._scan_queue).pack(side="right")

        # ── Settings + Options row (side by side) ─────────────────────────────
        config_row = tk.Frame(outer, bg=BG)
        config_row.pack(fill="x", pady=(0, 8))

        # Left: Model Settings
        settings_card = tk.Frame(config_row, bg=BG_PANEL, padx=16, pady=14)
        settings_card.pack(side="left", fill="both", expand=True, padx=(0, 4))

        section_label(settings_card, "Model Settings").pack(fill="x", pady=(0, 10))

        grid = tk.Frame(settings_card, bg=BG_PANEL)
        grid.pack(fill="x")
        grid.columnconfigure(1, weight=1)

        def lbl(parent, text, row, col):
            tk.Label(parent, text=text, font=("Consolas", 10), fg=TEXT_DIM,
                     bg=BG_PANEL, anchor="w").grid(row=row, column=col,
                                                    sticky="w", padx=(0, 8), pady=4)

        lbl(grid, "Whisper model", 0, 0)
        styled_combo(grid, ["tiny","base","small","medium","large-v2","large-v3"],
                     self.model_var, width=18).grid(row=0, column=1, sticky="ew")

        lbl(grid, "Compute type", 1, 0)
        styled_combo(grid, ["float16 (GPU recommended)",
                             "int8_float16 (lower VRAM)",
                             "int8 (CPU fallback)"],
                     self.compute_var, width=24).grid(row=1, column=1, sticky="ew")

        lbl(grid, "Source language", 2, 0)
        langs_src = ["auto-detect","Norwegian (no)","Swedish (sv)","Danish (da)",
                     "Finnish (fi)","German (de)","French (fr)","Spanish (es)",
                     "Italian (it)","Japanese (ja)","Korean (ko)","Chinese (zh)"]
        styled_combo(grid, langs_src, self.lang_var, width=18).grid(row=2, column=1, sticky="ew")

        lbl(grid, "Translate to", 3, 0)
        styled_combo(grid, [
            "English (en)", "Norwegian (no)", "Swedish (sv)", "Danish (da)",
            "German (de)", "French (fr)", "Spanish (es)", "None (keep original)",
        ], self.target_var, width=18).grid(row=3, column=1, sticky="ew")

        lbl(grid, "Batch size", 4, 0)
        styled_entry(grid, self.batch_size_var, width=6).grid(row=4, column=1, sticky="w")

        lbl(grid, "Translation engine", 5, 0)
        styled_combo(grid, [
            "Argos (local, offline)",
            "Google Translate (online)",
        ], self.trans_engine_var, width=24).grid(row=5, column=1, sticky="ew")

        # Right: Options
        opts_card = tk.Frame(config_row, bg=BG_PANEL, padx=16, pady=14)
        opts_card.pack(side="left", fill="both", expand=True, padx=(4, 0))

        section_label(opts_card, "Options").pack(fill="x", pady=(0, 8))

        def chk(parent, text, var):
            f = tk.Frame(parent, bg=BG_PANEL)
            cb = tk.Checkbutton(f, variable=var, bg=BG_PANEL,
                                activebackground=BG_PANEL,
                                selectcolor=BG_INPUT,
                                fg=ACCENT, activeforeground=ACCENT)
            cb.pack(side="left")
            tk.Label(f, text=text, font=("Consolas", 10), fg=TEXT,
                     bg=BG_PANEL).pack(side="left")
            return f

        chk(opts_card, "Skip if .en.srt exists", self.skip_var).pack(anchor="w", pady=2)
        chk(opts_card, "Skip if .no.srt exists", self.skip_no_var).pack(anchor="w", pady=2)
        chk(opts_card, "Save original-language .srt", self.keep_orig_var).pack(anchor="w", pady=2)
        chk(opts_card, "Dry run (list files only)", self.dry_run_var).pack(anchor="w", pady=2)

        tk.Frame(opts_card, bg=BORDER, height=1).pack(fill="x", pady=(8, 4))
        tk.Label(opts_card, text="DELETE BEFORE PROCESSING",
                 font=("Consolas", 8, "bold"), fg=TEXT_MUTED, bg=BG_PANEL).pack(anchor="w")
        chk(opts_card, "Delete existing .en.srt (replaces Bazarr)", self.delete_en_var).pack(anchor="w", pady=2)
        chk(opts_card, "Delete existing .no.srt", self.delete_no_var).pack(anchor="w", pady=2)

        # ── Log card ──────────────────────────────────────────────────────────
        log_card = tk.Frame(outer, bg=BG_PANEL, padx=16, pady=14)
        log_card.pack(fill="x", pady=(0, 8))

        section_label(log_card, "Output Log").pack(fill="x", pady=(0, 8))

        self.progress_var = tk.DoubleVar(value=0)
        style = ttk.Style()
        style.configure("Green.Horizontal.TProgressbar",
                         troughcolor=BG_INPUT, background=ACCENT,
                         bordercolor=BG_INPUT, lightcolor=ACCENT, darkcolor=ACCENT)
        self.pbar = ttk.Progressbar(log_card, variable=self.progress_var,
                                    maximum=100, style="Green.Horizontal.TProgressbar")
        self.pbar.pack(fill="x", pady=(0, 8))

        self.log_box = scrolledtext.ScrolledText(
            log_card, height=7, bg=BG_INPUT, fg=TEXT,
            insertbackground=TEXT, font=("Consolas", 9),
            relief="flat", borderwidth=0,
            highlightthickness=1, highlightbackground=BORDER)
        self.log_box.pack(fill="both", expand=True)
        self.log_box.tag_config("ok",   foreground=SUCCESS_COL)
        self.log_box.tag_config("info", foreground="#5b9bd5")
        self.log_box.tag_config("warn", foreground=WARN)
        self.log_box.tag_config("err",  foreground=ERROR_COL)
        self.log_box.tag_config("dim",  foreground=TEXT_MUTED)
        self.log_box.configure(state="disabled")

    # ── GPU detection ─────────────────────────────────────────────────────────
    def _check_gpu(self):
        try:
            import torch
            if torch.cuda.is_available():
                name = torch.cuda.get_device_name(0)
                vram = torch.cuda.get_device_properties(0).total_memory // (1024**3)
                self.gpu_badge.configure(text=f"  ✓ {name} ({vram}GB)  ",
                                         fg="#000", bg=ACCENT)
            else:
                self.gpu_badge.configure(text="  ⚠ No CUDA GPU found  ",
                                         fg="#000", bg=WARN)
        except ImportError:
            self.gpu_badge.configure(text="  torch not installed  ",
                                     fg=TEXT_DIM, bg=BG_INPUT)

    # ── Library popup ─────────────────────────────────────────────────────────
    def _open_library(self):
        LibraryWindow(self)

    def _queue_from_library(self, video_files: list):
        """Called by LibraryWindow to send files to the processor."""
        self._add_jobs(video_files)
        self._log(f"✓  {len(video_files)} file(s) added to queue from Library Manager.", "ok")
        if not self.is_running:
            self._start()

    # ── Stub methods used by old library UI (kept for _lib_scan_worker) ───────
    def _lib_browse(self):
        folder = filedialog.askdirectory(title="Select root library folder")
        if folder:
            self.folder_var.set(folder)

    def _lib_add_root(self):
        folder = self.folder_var.get().strip()
        if not folder or not os.path.isdir(folder):
            return
        if folder not in self.root_folders:
            self.root_folders.append(folder)
            self.library_db.data["__roots__"] = self.root_folders
            self.library_db.save()
        self.folder_var.set("")

    def _lib_load_from_cache(self):
        import json
        self.lib_entries = self.library_db.data.get("__entries__", [])

    def _lib_apply_filter(self):
        pass  # handled inside LibraryWindow

    def _lib_scan(self):
        if not self.root_folders:
            return
        t = threading.Thread(target=self._lib_scan_worker, daemon=True)
        t.start()

    def _lib_load_from_cache(self):
        """Load library entries from the JSON cache without touching the NAS."""
        import json, time
        self.lib_entries = []
        cached = self.library_db.data.get("__entries__", [])
        for e in cached:
            if any(e.get("root") == r or e.get("path", "").startswith(r) 
                   for r in self.root_folders):
                self.lib_entries.append(e)
        self._lib_apply_filter()

    def _lib_scan(self):
        """Trigger a background scan — called from LibraryWindow or manually."""
        if not self.root_folders:
            return
        t = threading.Thread(target=self._lib_scan_worker, daemon=True)
        t.start()

    def _lib_scan_worker(self):
        """Background scan worker — updates library_db, no UI references."""
        lang = self.scan_lang_var.get().strip() or "no"
        entries = []
        for root in self.root_folders:
            root_path = Path(root)
            if not root_path.exists():
                continue
            subfolders = sorted(
                [root_path] + [d for d in root_path.rglob("*") if d.is_dir()],
                key=lambda p: str(p).lower())
            processed_dirs = set()
            for d in subfolders:
                if d in processed_dirs:
                    continue
                try:
                    videos = [f for f in d.iterdir()
                              if f.is_file() and f.suffix.lower() in VIDEO_EXTENSIONS]
                except PermissionError:
                    continue
                if not videos:
                    continue
                if any(str(d).startswith(str(pd) + os.sep) for pd in processed_dirs):
                    continue
                all_vids = [f for f in d.rglob("*")
                            if f.is_file() and f.suffix.lower() in VIDEO_EXTENSIONS]
                statuses = []
                for v in all_vids:
                    cached = self.library_db.get(v)
                    status, our, srt, fp = scan_video_status(v, lang, cached)
                    self.library_db.update(v, status, our, srt, fp)
                    statuses.append(status)
                if not statuses:
                    continue
                status_set = set(statuses)
                if status_set == {"DONE"}:                              agg = "DONE"
                elif status_set == {"NEW"}:                             agg = "NEW"
                elif all(s in ("NEW","UNPROCESSED") for s in statuses): agg = "UNPROCESSED"
                elif "CHANGED" in status_set:                           agg = "CHANGED"
                elif "NEW" in status_set or "UNPROCESSED" in status_set: agg = "PARTIAL"
                elif "EXTERNAL" in status_set:                          agg = "EXTERNAL"
                else:                                                   agg = "DONE"
                entries.append({
                    "path":   str(d), "status": agg,
                    "total":  len(all_vids),
                    "done":   sum(1 for s in statuses if s == "DONE"),
                    "root":   root,
                })
                processed_dirs.add(d)
        self.lib_entries = entries
        self.library_db.data["__entries__"] = entries
        self.library_db.save()

    def _lib_apply_filter(self):
        pass  # handled inside LibraryWindow

    # ── Manual queue management ───────────────────────────────────────────────
    def _browse(self):
        folder = filedialog.askdirectory(title="Select folder to add to queue")
        if folder:
            self.folder_var.set(folder)

    def _add_to_queue(self):
        folder = self.folder_var.get().strip()
        if not folder or not os.path.isdir(folder):
            self.file_label.configure(text="⚠  Folder not found.", fg=WARN)
            return
        if folder in self.queue_folders:
            self.file_label.configure(text="⚠  Folder already in queue.", fg=WARN)
            return
        self.queue_folders.append(folder)
        self.folder_var.set("")
        self.file_label.configure(
            text=f"{len(self.queue_folders)} folder(s) — click Scan Folders to load files",
            fg=TEXT_DIM)

    def _queue_up(self): pass
    def _queue_down(self): pass

    def _queue_remove(self): pass  # legacy — use _job_remove

    def _queue_clear(self):
        self.queue_folders.clear()
        self._job_clear_all()

    def _refresh_queue_listbox(self, select_idx=None): pass  # no longer used

    def _scan_queue(self):
        if not self.queue_folders:
            self.file_label.configure(text="⚠  No folders added.", fg=WARN)
            return
        skip_en = self.skip_var.get()
        skip_no = self.skip_no_var.get()
        tgt_raw = self.target_var.get()
        tgt_lang = None if "None" in tgt_raw else tgt_raw.split("(")[-1].rstrip(")")
        files = []
        for folder in self.queue_folders:
            for root, dirs, fnames in os.walk(folder):
                dirs.sort(key=lambda d: (int(''.join(filter(str.isdigit, d)) or 0), d.lower()))
                for f in sorted(fnames):
                    p = Path(root) / f
                    if p.suffix.lower() not in VIDEO_EXTENSIONS:
                        continue
                    if skip_en and p.with_suffix('.en.srt').exists():
                        continue
                    if skip_no and p.with_suffix('.no.srt').exists():
                        continue
                    files.append(p)
        self._add_jobs(files)

    def _scan_folder(self):
        self._scan_queue()

    # ── Job list helpers ──────────────────────────────────────────────────────
    def _add_jobs(self, paths: list):
        """Add a list of Path objects to the job list, skipping duplicates."""
        existing = {j["path"] for j in self.job_list}
        added = 0
        for p in paths:
            if p in existing:
                continue
            iid = self.job_tree.insert("", "end",
                                        values=("○", p.name),
                                        tags=("pending",))
            self.job_list.append({"path": p, "status": "pending", "iid": iid})
            existing.add(p)
            added += 1
        self._update_job_label()
        if added:
            # Scroll to first pending item
            for j in self.job_list:
                if j["status"] == "pending":
                    self.job_tree.see(j["iid"])
                    break

    def _set_job_status(self, iid: str, status: str):
        icons = {"pending": "○", "running": "▶", "done": "✓", "error": "✗"}
        self.job_tree.item(iid, values=(icons.get(status, "?"),
                                        self.job_tree.item(iid)["values"][1]),
                            tags=(status,))
        self.job_tree.see(iid)

    def _job_remove(self):
        sel = self.job_tree.selection()
        for iid in sel:
            # Don't remove currently running item
            job = next((j for j in self.job_list if j["iid"] == iid), None)
            if job and job["status"] == "running":
                continue
            self.job_tree.delete(iid)
            self.job_list = [j for j in self.job_list if j["iid"] != iid]
        self._update_job_label()

    def _job_clear_done(self):
        for j in list(self.job_list):
            if j["status"] in ("done", "error"):
                self.job_tree.delete(j["iid"])
                self.job_list.remove(j)
        self._update_job_label()

    def _job_clear_all(self):
        for j in list(self.job_list):
            if j["status"] != "running":
                self.job_tree.delete(j["iid"])
                self.job_list.remove(j)
        self._update_job_label()

    def _update_job_label(self):
        total   = len(self.job_list)
        pending = sum(1 for j in self.job_list if j["status"] == "pending")
        done    = sum(1 for j in self.job_list if j["status"] == "done")
        errors  = sum(1 for j in self.job_list if j["status"] == "error")
        if total == 0:
            self.file_label.configure(text="Queue is empty.", fg=TEXT_MUTED)
        else:
            parts = [f"{pending} pending", f"{done} done"]
            if errors:
                parts.append(f"{errors} failed")
            self.file_label.configure(text="  |  ".join(parts), fg=TEXT_DIM)

    # ── Log helpers ───────────────────────────────────────────────────────────
    def _log(self, msg, tag=""):
        self.log_box.configure(state="normal")
        self.log_box.insert("end", msg + "\n", tag)
        self.log_box.see("end")
        self.log_box.configure(state="disabled")

    def _clear_log(self):
        self.log_box.configure(state="normal")
        self.log_box.delete("1.0", "end")
        self.log_box.configure(state="disabled")
        self.progress_var.set(0)

    def _poll_log(self):
        try:
            while True:
                msg, tag = log_queue.get_nowait()
                self._log(msg, tag)
        except queue.Empty:
            pass
        self.after(100, self._poll_log)

    # ── Start processing ──────────────────────────────────────────────────────
    def _start(self):
        if self.is_running:
            return
        # If manual folders were added but not scanned yet, scan now
        if self.queue_folders and not any(j["status"] == "pending" for j in self.job_list):
            self._scan_queue()
        pending = [j for j in self.job_list if j["status"] == "pending"]
        if not pending:
            self._log("⚠  No pending files in queue. Add folders or use Library Manager.", "warn")
            return
        self.is_running = True
        self.run_btn.configure_text("⏳  Running…")
        self.progress_var.set(0)
        t = threading.Thread(target=self._run_batch, daemon=True)
        t.start()

    def _run_batch(self):
        def q(msg, tag=""):
            log_queue.put((msg, tag))

        try:
            import torch
            import whisperx
        except ImportError as e:
            q(f"✗  Missing dependency: {e}", "err")
            q("   Run:  pip install whisperx transformers sentencepiece sacremoses torch", "warn")
            self._finish()
            return

        model_name   = self.model_var.get()
        compute_raw  = self.compute_var.get().split()[0]
        lang_raw     = self.lang_var.get()
        target_raw   = self.target_var.get()
        trans_engine = self.trans_engine_var.get()
        keep_orig    = self.keep_orig_var.get()
        dry_run      = self.dry_run_var.get()
        delete_en    = self.delete_en_var.get()
        delete_no    = self.delete_no_var.get()
        batch_size   = int(self.batch_size_var.get() or 16)

        src_lang = None if lang_raw == "auto-detect" else lang_raw.split("(")[-1].rstrip(")")
        tgt_lang = None if "None" in target_raw else target_raw.split("(")[-1].rstrip(")")

        device = "cuda" if torch.cuda.is_available() else "cpu"

        # Load Whisper model
        q(f"Loading model '{model_name}' …", "info")
        try:
            task = "translate" if tgt_lang == "en" and src_lang and src_lang != "en" else "transcribe"
            whisper_model = whisperx.load_model(
                model_name, device, compute_type=compute_raw,
                language=src_lang
            )
            q(f"✓  Model loaded.", "ok")
        except Exception as e:
            q(f"✗  Failed to load model: {e}", "err")
            self._finish()
            return

        # ── Translation engines ───────────────────────────────────────────────
        LANG_MAP = {
            "no": "nb", "nb": "nb", "sv": "sv", "da": "da",
            "de": "de", "fr": "fr", "es": "es", "fi": "fi",
            "nl": "nl", "it": "it", "pl": "pl", "en": "en",
            "ja": "ja", "ko": "ko", "zh": "zh",
        }
        GOOGLE_LANG = {**LANG_MAP, "nb": "no"}

        # Cache loaded translation models
        ct2_model_cache = {}

        # Enable Argos GPU usage, disable Stanza SBD to avoid interference
        import os as _os
        _os.environ["ARGOS_DEVICE_TYPE"] = "cuda" if device == "cuda" else "cpu"
        _os.environ["ARGOS_STANZA_AVAILABLE"] = "False"

        def translate_ct2(texts, src, tgt):
            """Translate using Argos Translate with GPU support."""
            try:
                import argostranslate.package as ap
                import argostranslate.translate as at

                al_src = LANG_MAP.get(src, src)
                al_tgt = LANG_MAP.get(tgt, tgt)
                key = (al_src, al_tgt)

                if key not in ct2_model_cache:
                    tgt_codes = ["nb", "no"] if al_tgt in ("nb", "no") else [al_tgt]

                    installed = at.get_installed_languages()
                    src_lang  = next((l for l in installed if l.code == al_src), None)
                    tgt_lang  = None
                    for tc in tgt_codes:
                        tgt_lang = next((l for l in installed if l.code == tc), None)
                        if tgt_lang:
                            al_tgt = tc
                            break

                    if not src_lang or not tgt_lang:
                        q(f"  Downloading Argos pack {al_src}→{tgt_codes[0]}…", "info")
                        try:
                            ap.update_package_index()
                            available = ap.get_available_packages()
                            pkg = next((p for p in available
                                       if p.from_code == al_src and p.to_code in tgt_codes), None)
                            if not pkg:
                                q(f"  ⚠  No Argos pack for {al_src}→{tgt_codes}, falling back to Google", "warn")
                                return translate_google(texts, src, tgt)
                            ap.install_from_path(pkg.download())
                            q(f"  ✓  Pack installed", "ok")
                            installed = at.get_installed_languages()
                            src_lang  = next((l for l in installed if l.code == al_src), None)
                            for tc in tgt_codes:
                                tgt_lang = next((l for l in installed if l.code == tc), None)
                                if tgt_lang:
                                    al_tgt = tc
                                    break
                        except Exception as e:
                            q(f"  ⚠  Pack install failed: {e}, falling back to Google", "warn")
                            return translate_google(texts, src, tgt)

                    if not src_lang or not tgt_lang:
                        q(f"  ⚠  Languages not available, falling back to Google", "warn")
                        return translate_google(texts, src, tgt)

                    translation = src_lang.get_translation(tgt_lang)
                    if not translation:
                        q(f"  ⚠  No translation object for {al_src}→{al_tgt}, falling back to Google", "warn")
                        return translate_google(texts, src, tgt)

                    ct2_model_cache[key] = translation
                    q(f"  ✓  Argos ready ({al_src}→{al_tgt}, GPU: {device == 'cuda'})", "ok")

                translation = ct2_model_cache[key]
                results = list(texts)
                for i, text in enumerate(texts):
                    if text.strip():
                        results[i] = translation.translate(text)
                return results

            except ImportError:
                q("  ⚠  argostranslate not installed. Run: pip install argostranslate", "warn")
                q("  ⚠  Falling back to Google Translate", "warn")
                return translate_google(texts, src, tgt)
            except Exception as e:
                q(f"  ⚠  Argos error: {e}, falling back to Google", "warn")
                return translate_google(texts, src, tgt)

        def translate_google(texts, src, tgt):
            import time
            try:
                from deep_translator import GoogleTranslator
                gl_src = GOOGLE_LANG.get(src, src)
                gl_tgt = GOOGLE_LANG.get(tgt, tgt)
                SEPARATOR = " ||| "
                MAX_CHARS = 4500
                results = [""] * len(texts)
                batch_indices = []
                batch_chars = 0
                batch_lines = []

                def flush_batch():
                    if not batch_lines:
                        return
                    joined = SEPARATOR.join(batch_lines)
                    for attempt in range(3):
                        try:
                            translator = GoogleTranslator(source=gl_src, target=gl_tgt)
                            translated_joined = translator.translate(joined)
                            if not translated_joined:
                                raise ValueError("Empty response")
                            parts = translated_joined.split(SEPARATOR)
                            if len(parts) == len(batch_indices):
                                for idx, part in zip(batch_indices, parts):
                                    results[idx] = part.strip()
                            else:
                                for i, idx in enumerate(batch_indices):
                                    results[idx] = parts[i].strip() if i < len(parts) else texts[idx]
                            time.sleep(0.3)
                            break
                        except Exception:
                            if attempt < 2:
                                wait = (attempt + 1) * 3
                                q(f"  ⚠  Google attempt {attempt+1} failed, retrying in {wait}s…", "warn")
                                time.sleep(wait)
                            else:
                                q(f"  ⚠  Google translation failed, keeping original", "warn")
                                for idx in batch_indices:
                                    results[idx] = texts[idx]
                    batch_indices.clear()
                    batch_lines.clear()

                for i, text in enumerate(texts):
                    if not text.strip():
                        results[i] = text
                        continue
                    line_len = len(text) + len(SEPARATOR)
                    if batch_chars + line_len > MAX_CHARS and batch_lines:
                        flush_batch()
                        batch_chars = 0
                    batch_indices.append(i)
                    batch_lines.append(text)
                    batch_chars += line_len
                flush_batch()

                translated_count = sum(1 for i, r in enumerate(results)
                                       if r.strip() and r.strip() != texts[i].strip())
                if translated_count == 0 and any(t.strip() for t in texts):
                    q(f"  ⚠  Translation appears to have failed (all text unchanged)", "warn")
                return results

            except ImportError:
                q("  ⚠  deep-translator not installed. Run: pip install deep-translator", "warn")
                return texts

        def translate_texts(texts, src, tgt):
            if "Argos" in trans_engine:
                return translate_ct2(texts, src, tgt)
            else:
                return translate_google(texts, src, tgt)

        def fix_caps(text):
            # Fix ALL CAPS output from Whisper
            if text == text.upper() and len(text) > 3:
                return text.capitalize()
            return text

        pending = [j for j in self.job_list if j["status"] == "pending"]
        total = len(pending)
        done  = 0

        q(f"─── Starting batch ───────────────────────────", "dim")
        q(f"  Model    : {model_name}", "info")
        q(f"  Device   : {device} ({compute_raw})", "info")
        q(f"  Engine   : {trans_engine}", "info")
        q(f"  Files    : {total}", "info")
        if dry_run:
            q("  Mode     : DRY RUN", "warn")
        q("", "dim")

        if dry_run:
            for j in pending:
                q(f"  [would process] {j['path']}", "dim")
            q(f"\nDry run complete. {total} file(s) listed.", "ok")
            self._finish()
            return

        for idx, job in enumerate(pending):
            video = job["path"]
            iid   = job["iid"]
            rel   = video.name

            # Mark as running in UI
            job["status"] = "running"
            self.after(0, lambda i=iid: self._set_job_status(i, "running"))
            q(f"\n[{idx+1}/{total}]  {rel}", "info")
            self.after(0, lambda r=rel, i=idx, t=total:
                       self.status_label.configure(text=f"[{i+1}/{t}] {r}"))

            # Delete existing subtitle files if requested
            if delete_en or delete_no:
                import glob
                base = str(video.with_suffix(""))
                for existing in glob.glob(base + "*.srt"):
                    ep = Path(existing)
                    name = ep.name.lower()
                    if delete_en and (".en." in name or name.endswith(".en.srt")):
                        ep.unlink()
                        q(f"  deleted: {ep.name}", "dim")
                    elif delete_no and (".no." in name or ".nb." in name or
                                        name.endswith(".no.srt") or name.endswith(".nb.srt")):
                        ep.unlink()
                        q(f"  deleted: {ep.name}", "dim")

            try:
                import whisperx as wx
                import torch as _t
                import gc

                # Clear GPU memory before each file
                _t.cuda.empty_cache()
                gc.collect()

                audio  = wx.load_audio(str(video))
                result = whisper_model.transcribe(audio, batch_size=batch_size)
                segs   = result["segments"]
                detected = result.get("language", src_lang or "?")
                q(f"  language detected: {detected}", "dim")

                # Run alignment on GPU to get word-level timestamps
                try:
                    align_model, align_meta = wx.load_align_model(
                        language_code=detected, device=device)
                    aligned = wx.align(segs, align_model, align_meta, audio, device,
                                       return_char_alignments=False)
                    segs = aligned["segments"]
                    del align_model
                    _t.cuda.empty_cache()
                    gc.collect()
                    q(f"  aligned", "dim")
                except Exception as e:
                    q(f"  ⚠  alignment skipped, using proportional split", "warn")
                    try:
                        _t.cuda.empty_cache()
                        gc.collect()
                    except Exception:
                        pass

                # Fix ALL CAPS segments from Whisper
                for s in segs:
                    s["text"] = fix_caps(s["text"].strip())

                if keep_orig:
                    orig_path = video.with_suffix(f".{detected}.srt")
                    orig_path.write_text(_to_srt(segs), encoding="utf-8-sig")
                    q(f"  saved: {orig_path.name}", "dim")

                # Translate if target language differs from detected language
                if tgt_lang and tgt_lang != detected:
                    q(f"  translating {detected}→{tgt_lang} ({trans_engine.split('(')[0].strip()})…", "dim")
                    texts = [s["text"].strip() for s in segs]
                    translated = translate_texts(texts, detected, tgt_lang)
                    for s, t in zip(segs, translated):
                        s["text"] = t
                        # Clear word-level data so _to_srt uses translated text
                        # (word entries still contain original English)
                        s.pop("words", None)
                    q(f"  translated {detected}→{tgt_lang}", "dim")

                # Plex naming: ShowName.S01E01.LANG.srt next to video file
                out_lang = tgt_lang if tgt_lang else detected
                out_path = video.with_suffix(f".{out_lang}.srt")
                out_path.write_text(_to_srt(segs), encoding="utf-8-sig")
                q(f"  ✓  saved: {out_path.name}", "ok")

                # Update library DB immediately so status reflects without a rescan
                fp = file_fingerprint(video)
                self.library_db.update(video, "DONE", True, str(out_path), fp)
                self._update_lib_entry(video, "DONE")

                # Mark job done in UI
                job["status"] = "done"
                self.after(0, lambda i=iid: self._set_job_status(i, "done"))

            except Exception as e:
                q(f"  ✗  error: {e}", "err")
                job["status"] = "error"
                self.after(0, lambda i=iid: self._set_job_status(i, "error"))
                try:
                    import torch as _t, gc
                    _t.cuda.empty_cache()
                    gc.collect()
                    if "CUDA error" in str(e):
                        q(f"  ↺  CUDA error detected — reloading model…", "warn")
                        try:
                            whisper_model = whisperx.load_model(
                                model_name, device, compute_type=compute_raw,
                                language=src_lang
                            )
                            q(f"  ✓  Model reloaded.", "ok")
                        except Exception as reload_err:
                            q(f"  ✗  Could not reload model: {reload_err}", "err")
                    else:
                        q(f"  ↺  GPU memory cleared, continuing…", "warn")
                except Exception:
                    pass

            done += 1
            pct = (done / total) * 100
            self.after(0, lambda p=pct: self.progress_var.set(p))
            self.after(0, self._update_job_label)

        q(f"\n─── Done! {done}/{total} file(s) processed. ───", "ok")
        self._finish()

    def _finish(self):
        self.is_running = False
        self.library_db.save()
        self.after(0, lambda: self.run_btn.configure_text("▶  Start Processing"))
        self.after(0, lambda: self.status_label.configure(text="Finished. Click Scan to refresh library."))

    def _update_lib_entry(self, video: Path, status: str):
        """Update the in-memory lib_entries for a single file after processing."""
        video_str = str(video)
        for entry in self.lib_entries:
            episodes = entry.get("episodes", [])
            for ep in episodes:
                if ep.get("path") == video_str:
                    ep["status"] = status
                    ep["our"]    = True
                    break
            else:
                continue
            # Recompute aggregate status for this folder entry
            all_statuses = [e["status"] for e in episodes]
            status_set   = set(all_statuses)
            if status_set == {"DONE"}:
                agg = "DONE"
            elif status_set == {"NEW"}:
                agg = "NEW"
            elif all(s in ("NEW", "UNPROCESSED") for s in all_statuses):
                agg = "UNPROCESSED"
            elif "CHANGED" in status_set:
                agg = "CHANGED"
            elif "NEW" in status_set or "UNPROCESSED" in status_set:
                agg = "PARTIAL"
            elif "EXTERNAL" in status_set:
                agg = "EXTERNAL"
            else:
                agg = "DONE"
            entry["status"] = agg
            entry["done"]   = sum(1 for s in all_statuses if s == "DONE")
            break
        # Persist the updated entries to disk
        self.library_db.data["__entries__"] = self.lib_entries
        self.library_db.save()

    def _quit(self):
        self.library_db.data["__roots__"] = self.root_folders
        self.library_db.save()
        self.status_label.configure(text="Saved. Goodbye.")
        self.after(300, self.destroy)


# ─── SRT helper ───────────────────────────────────────────────────────────────
def _to_srt(segments):
    def ts(t):
        t = max(0.0, float(t))
        h  = int(t // 3600)
        m  = int((t % 3600) // 60)
        s  = int(t % 60)
        ms = int(round((t - int(t)) * 1000))
        return f"{h:02}:{m:02}:{s:02},{ms:03}"

    def split_segment(seg, max_chars=80):
        """Split a long segment using word timings if available, else proportional."""
        text = seg.get("text", "").strip()
        start = float(seg.get("start", 0))
        end   = float(seg.get("end", 0))
        duration = end - start
        words = seg.get("words", [])

        if len(text) <= max_chars and not words:
            return [{"start": start, "end": end, "text": text}]

        # Use word-level timings if available (from alignment)
        if words:
            result = []
            chunk_words = []
            chunk_start = None

            for w in words:
                w_start = w.get("start")
                w_end   = w.get("end")
                w_word  = w.get("word", "").strip()
                if not w_word:
                    continue
                if chunk_start is None:
                    chunk_start = w_start if w_start is not None else start

                chunk_words.append(w)
                chunk_text = " ".join(x.get("word","").strip() for x in chunk_words)

                if len(chunk_text) >= max_chars and len(chunk_words) > 1:
                    # Save chunk up to previous word
                    prev = chunk_words[:-1]
                    prev_text = " ".join(x.get("word","").strip() for x in prev)
                    prev_end  = prev[-1].get("end") or end
                    result.append({"start": chunk_start, "end": prev_end, "text": prev_text})
                    chunk_words = [w]
                    chunk_start = w_start if w_start is not None else prev_end

            if chunk_words:
                chunk_text = " ".join(x.get("word","").strip() for x in chunk_words)
                chunk_end  = chunk_words[-1].get("end") or end
                result.append({"start": chunk_start, "end": chunk_end, "text": chunk_text})

            return result if result else [{"start": start, "end": end, "text": text}]

        # Split on sentence boundaries first, then on commas if still too long
        import re
        # Split on .!? followed by space, or on comma+space
        parts = re.split(r'(?<=[.!?])\s+', text)
        if len(parts) == 1:
            parts = re.split(r'(?<=,)\s+', text)
        if len(parts) == 1:
            # Last resort: split roughly in half at a space
            mid = len(text) // 2
            split_at = text.rfind(' ', 0, mid + 20)
            if split_at == -1:
                split_at = mid
            parts = [text[:split_at].strip(), text[split_at:].strip()]

        # Merge very short parts with the next one
        merged = []
        buf = ""
        for p in parts:
            if not p.strip():
                continue
            if buf and len(buf) + len(p) + 1 <= max_chars:
                buf = buf + " " + p
            else:
                if buf:
                    merged.append(buf)
                buf = p
        if buf:
            merged.append(buf)

        if not merged:
            return [{"start": start, "end": end, "text": text}]

        # Assign timing proportionally by character count
        total_chars = sum(len(p) for p in merged)
        result = []
        t = start
        for p in merged:
            ratio = len(p) / total_chars if total_chars > 0 else 1 / len(merged)
            seg_duration = duration * ratio
            result.append({
                "start": round(t, 3),
                "end":   round(min(t + seg_duration, end), 3),
                "text":  p.strip()
            })
            t += seg_duration

        return result

    lines = []
    counter = 1
    for seg in segments:
        for chunk in split_segment(seg):
            text = chunk.get("text", "").strip()
            if not text:
                continue
            lines.append(str(counter))
            lines.append(f"{ts(chunk['start'])} --> {ts(chunk['end'])}")
            lines.append(text)
            lines.append("")
            counter += 1
    content = "\n".join(lines)
    return OUR_TAG + "\n" + content



# ─── Library Window ───────────────────────────────────────────────────────────
class LibraryWindow(tk.Toplevel):
    def __init__(self, app):
        super().__init__(app)
        self.app = app
        self.title("Library Manager")
        self.configure(bg=BG)
        self.geometry("1100x700")
        self.minsize(800, 500)
        self.resizable(True, True)

        self.lib_entries  = list(app.lib_entries)
        self.filter_var   = tk.StringVar(value="ALL")
        self.search_var   = tk.StringVar(value="")
        self.scan_lang_var = app.scan_lang_var
        self.folder_var   = tk.StringVar(value="")
        self._build()
        self._populate()

    def _build(self):
        # ── Top bar ───────────────────────────────────────────────────────────
        top = tk.Frame(self, bg=BG_PANEL, padx=16, pady=10)
        top.pack(fill="x")

        # Root management
        r1 = tk.Frame(top, bg=BG_PANEL)
        r1.pack(fill="x", pady=(0, 6))
        tk.Label(r1, text="Root:", font=("Consolas", 9), fg=TEXT_DIM,
                 bg=BG_PANEL).pack(side="left", padx=(0, 6))
        styled_entry(r1, self.folder_var, width=50).pack(side="left", fill="x",
                                                          expand=True, padx=(0, 8))
        FlatButton(r1, "Browse", command=self._browse_root).pack(side="left")
        FlatButton(r1, "Add Root", command=self._add_root).pack(side="left", padx=(6, 0))

        # Roots list
        self.roots_lb = tk.Listbox(top, height=2, bg=BG_INPUT, fg=TEXT_DIM,
                                    font=("Consolas", 9), relief="flat",
                                    highlightthickness=1, highlightbackground=BORDER,
                                    selectbackground=BG_HOVER, activestyle="none")
        for r in self.app.root_folders:
            self.roots_lb.insert("end", r)
        self.roots_lb.pack(fill="x", pady=(0, 6))

        # Search + filter + scan
        r2 = tk.Frame(top, bg=BG_PANEL)
        r2.pack(fill="x")
        tk.Label(r2, text="Search:", font=("Consolas", 9), fg=TEXT_DIM,
                 bg=BG_PANEL).pack(side="left")
        self.search_entry = styled_entry(r2, self.search_var, width=24)
        self.search_entry.pack(side="left", padx=(4, 16))
        self.search_var.trace_add("write", lambda *a: self._populate())
        tk.Label(r2, text="Lang:", font=("Consolas", 9), fg=TEXT_DIM,
                 bg=BG_PANEL).pack(side="left")
        styled_entry(r2, self.scan_lang_var, width=4).pack(side="left", padx=(4, 16))
        tk.Label(r2, text="Filter:", font=("Consolas", 9), fg=TEXT_DIM,
                 bg=BG_PANEL).pack(side="left")
        for f in ["ALL", "NEW", "UNPROCESSED", "DONE", "PARTIAL", "CHANGED", "EXTERNAL"]:
            tk.Radiobutton(r2, text=f, variable=self.filter_var, value=f,
                           command=self._populate,
                           bg=BG_PANEL, fg=TEXT, selectcolor=BG_INPUT,
                           activebackground=BG_PANEL, activeforeground=ACCENT,
                           font=("Consolas", 9)).pack(side="left", padx=(0, 5))
        FlatButton(r2, "Scan Library", command=self._scan).pack(side="right")
        FlatButton(r2, "Remove Root", command=self._remove_root).pack(side="right", padx=(0, 6))

        # ── Tree ──────────────────────────────────────────────────────────────
        tree_outer = tk.Frame(self, bg=BG)
        tree_outer.pack(fill="both", expand=True, padx=16, pady=8)

        style = ttk.Style()
        style.configure("LW.Treeview",
                        background=BG_INPUT, foreground=TEXT,
                        fieldbackground=BG_INPUT, rowheight=20,
                        font=("Consolas", 9))
        style.configure("LW.Treeview.Heading",
                        background=BG_PANEL, foreground=TEXT_DIM,
                        font=("Consolas", 9, "bold"), relief="flat")
        style.map("LW.Treeview",
                  background=[("selected", "#1a2a1a")],
                  foreground=[("selected", ACCENT)])

        vsb = tk.Scrollbar(tree_outer, orient="vertical",
                            bg=BG_INPUT, troughcolor=BG_INPUT, width=10)
        hsb = tk.Scrollbar(tree_outer, orient="horizontal",
                            bg=BG_INPUT, troughcolor=BG_INPUT, width=10)
        self.tree = ttk.Treeview(tree_outer, style="LW.Treeview",
                                  columns=("status", "files", "done", "path"),
                                  show="tree headings",
                                  yscrollcommand=vsb.set,
                                  xscrollcommand=hsb.set,
                                  selectmode="extended")
        vsb.config(command=self.tree.yview)
        hsb.config(command=self.tree.xview)
        self.tree.heading("#0",     text="NAME")
        self.tree.heading("status", text="STATUS")
        self.tree.heading("files",  text="FILES")
        self.tree.heading("done",   text="DONE")
        self.tree.heading("path",   text="PATH")
        self.tree.column("#0",     width=280, stretch=False)
        self.tree.column("status", width=100, stretch=False)
        self.tree.column("files",  width=60,  stretch=False, anchor="center")
        self.tree.column("done",   width=60,  stretch=False, anchor="center")
        self.tree.column("path",   width=500, stretch=True)
        # Tags
        for tag, color in [("NEW","#5b9bd5"),("UNPROCESSED","#8888cc"),
                            ("DONE",SUCCESS_COL),("PARTIAL","#c08030"),
                            ("CHANGED",WARN),("EXTERNAL",TEXT_DIM)]:
            self.tree.tag_configure(tag, foreground=color)
        self.tree.pack(side="left", fill="both", expand=True)
        vsb.pack(side="right", fill="y")

        # ── Bottom bar ────────────────────────────────────────────────────────
        bot = tk.Frame(self, bg=BG_PANEL, padx=16, pady=10)
        bot.pack(fill="x", side="bottom")
        FlatButton(bot, "Select All",         command=self._sel_all).pack(side="left", padx=(0,6))
        FlatButton(bot, "Select NEW",         command=lambda: self._sel_status("NEW")).pack(side="left", padx=(0,6))
        FlatButton(bot, "Select UNPROCESSED", command=lambda: self._sel_status("UNPROCESSED")).pack(side="left", padx=(0,6))
        FlatButton(bot, "Select CHANGED",     command=lambda: self._sel_status("CHANGED")).pack(side="left", padx=(0,6))
        FlatButton(bot, "Expand All",         command=self._expand_all).pack(side="left", padx=(0,6))
        FlatButton(bot, "Collapse All",       command=self._collapse_all).pack(side="left", padx=(0,6))
        self.count_label = tk.Label(bot, text="", font=("Consolas", 9),
                                    fg=TEXT_MUTED, bg=BG_PANEL)
        self.count_label.pack(side="left", padx=(12, 0))
        FlatButton(bot, "Close", command=self.destroy).pack(side="right", padx=(8, 0))
        FlatButton(bot, "▶  Process Selected", command=self._process,
                   accent=True).pack(side="right")
        self.scan_status = tk.Label(bot, text="", font=("Consolas", 9),
                                    fg=WARN, bg=BG_PANEL)
        self.scan_status.pack(side="right", padx=(0, 16))

    def _browse_root(self):
        folder = filedialog.askdirectory(title="Select root library folder",
                                         parent=self)
        if folder:
            self.folder_var.set(folder)

    def _add_root(self):
        folder = self.folder_var.get().strip()
        if not folder or not os.path.isdir(folder):
            return
        if folder not in self.app.root_folders:
            self.app.root_folders.append(folder)
            self.app.library_db.data["__roots__"] = self.app.root_folders
            self.app.library_db.save()
            self.roots_lb.insert("end", folder)
        self.folder_var.set("")
        self.scan_status.configure(text=f"Root added. Click Scan to index.")

    def _remove_root(self):
        sel = self.roots_lb.curselection()
        if not sel:
            return
        folder = self.roots_lb.get(sel[0])
        if folder in self.app.root_folders:
            self.app.root_folders.remove(folder)
            self.app.library_db.data["__roots__"] = self.app.root_folders
            self.app.library_db.save()
        self.roots_lb.delete(sel[0])
        self.lib_entries = [e for e in self.lib_entries
                            if not e.get("path", "").startswith(folder)]
        self._populate()

    def _scan(self):
        if not self.app.root_folders:
            self.scan_status.configure(text="Add a root folder first.")
            return
        self.scan_status.configure(text="Scanning…")
        self.update_idletasks()
        t = threading.Thread(target=self._scan_worker, daemon=True)
        t.start()

    def _scan_worker(self):
        lang = self.scan_lang_var.get().strip() or "no"
        entries = []
        for root in self.app.root_folders:
            root_path = Path(root)
            if not root_path.exists():
                continue
            self.after(0, lambda r=root: self.scan_status.configure(
                text=f"Scanning {Path(r).name}…"))
            subfolders = sorted(
                [root_path] + [d for d in root_path.rglob("*") if d.is_dir()],
                key=lambda p: str(p).lower())
            processed_dirs = set()
            for d in subfolders:
                if d in processed_dirs:
                    continue
                try:
                    videos = [f for f in d.iterdir()
                              if f.is_file() and f.suffix.lower() in VIDEO_EXTENSIONS]
                except PermissionError:
                    continue
                if not videos:
                    continue
                if any(str(d).startswith(str(pd) + os.sep) for pd in processed_dirs):
                    continue
                all_vids = sorted([f for f in d.rglob("*")
                                   if f.is_file() and f.suffix.lower() in VIDEO_EXTENSIONS])
                ep_statuses = []
                episodes = []
                for v in all_vids:
                    cached = self.app.library_db.get(v)
                    status, our, srt, fp = scan_video_status(v, lang, cached)
                    self.app.library_db.update(v, status, our, srt, fp)
                    ep_statuses.append(status)
                    episodes.append({"path": str(v), "status": status,
                                     "our": our, "srt": srt})

                if not ep_statuses:
                    continue

                status_set = set(ep_statuses)
                if status_set == {"DONE"}:
                    agg = "DONE"
                elif status_set == {"NEW"}:
                    agg = "NEW"
                elif all(s in ("NEW", "UNPROCESSED") for s in ep_statuses):
                    agg = "UNPROCESSED"
                elif "CHANGED" in status_set:
                    agg = "CHANGED"
                elif "NEW" in status_set or "UNPROCESSED" in status_set:
                    agg = "PARTIAL"
                elif "EXTERNAL" in status_set:
                    agg = "EXTERNAL"
                else:
                    agg = "DONE"

                entries.append({
                    "path":     str(d),
                    "status":   agg,
                    "total":    len(all_vids),
                    "done":     sum(1 for s in ep_statuses if s == "DONE"),
                    "root":     root,
                    "episodes": episodes,
                })
                processed_dirs.add(d)
                self.after(0, lambda n=len(entries): self.scan_status.configure(
                    text=f"Scanning… {n} folders found"))

        self.lib_entries = entries
        self.app.lib_entries = entries
        self.app.library_db.data["__entries__"] = entries
        self.app.library_db.save()
        self.after(0, self._populate)
        self.after(0, lambda: self.scan_status.configure(
            text=f"Done — {len(entries)} folders indexed."))

    def _populate(self):
        self.tree.delete(*self.tree.get_children())
        filt   = self.filter_var.get()
        search = self.search_var.get().lower().strip()
        shown  = 0

        for e in self.lib_entries:
            # Filter by status
            if filt != "ALL" and e["status"] != filt:
                continue
            # Filter by search
            name = Path(e["path"]).name
            if search and search not in name.lower() and search not in e["path"].lower():
                continue

            # Relative display name
            try:
                rel = str(Path(e["path"]).relative_to(e["root"]))
                if not rel or rel == ".":
                    rel = Path(e["root"]).name
            except Exception:
                rel = name

            badge = {"NEW":         "● NEW",
                     "UNPROCESSED":  "○ UNPROCESSED",
                     "DONE":         "✓ DONE",
                     "PARTIAL":      "◑ PARTIAL",
                     "CHANGED":      "▲ CHANGED",
                     "EXTERNAL":     "~ EXTERNAL"}.get(e["status"], e["status"])

            parent = self.tree.insert("", "end", text=rel,
                                       values=(badge, e["total"], e["done"], e["path"]),
                                       tags=(e["status"],), open=False)

            # Insert episode children
            for ep in e.get("episodes", []):
                ep_name = Path(ep["path"]).name
                if search and search not in ep_name.lower():
                    continue
                ep_badge = {"NEW":        "● NEW",
                            "UNPROCESSED":"○ UNPROCESSED",
                            "DONE":       "✓ DONE",
                            "CHANGED":    "▲ CHANGED",
                            "EXTERNAL":   "~ EXTERNAL"}.get(ep["status"], ep["status"])
                srt_name = Path(ep["srt"]).name if ep.get("srt") else ""
                detail = f"  {ep_name}"
                if srt_name:
                    detail += f"   [{srt_name}]"
                self.tree.insert(parent, "end",
                                  text=detail,
                                  values=(ep_badge, "", "", ep["path"]),
                                  tags=(ep["status"],))
            shown += 1

        self.count_label.configure(
            text=f"{shown} / {len(self.lib_entries)} folders shown")

    def _sel_all(self):
        # Select only top-level items
        self.tree.selection_set(self.tree.get_children())

    def _sel_status(self, status):
        self.tree.selection_remove(self.tree.get_children(""))
        for iid in self.tree.get_children(""):
            if status in self.tree.item(iid)["tags"]:
                self.tree.selection_add(iid)

    def _expand_all(self):
        for iid in self.tree.get_children():
            self.tree.item(iid, open=True)

    def _collapse_all(self):
        for iid in self.tree.get_children():
            self.tree.item(iid, open=False)

    def _process(self):
        sel = self.tree.selection()
        if not sel:
            self.scan_status.configure(text="Select folders or episodes first.")
            return
        lang = self.scan_lang_var.get().strip() or "no"
        skip_done = self.app.skip_no_var.get()
        video_files = []

        for iid in sel:
            parent = self.tree.parent(iid)
            if parent:
                # It's an episode — add directly
                path_val = self.tree.item(iid)["values"][3]
                # Strip srt_info suffix if present
                path_str = path_val.split("  ")[0].strip()
                p = Path(path_str)
                if p.exists() and p.suffix.lower() in VIDEO_EXTENSIONS:
                    video_files.append(p)
            else:
                # It's a folder — walk it
                folder = Path(self.tree.item(iid)["values"][3])
                for root, dirs, files in os.walk(folder):
                    dirs.sort(key=lambda d: (
                        int(''.join(filter(str.isdigit, d)) or 0), d.lower()))
                    for f in sorted(files):
                        p = Path(root) / f
                        if p.suffix.lower() not in VIDEO_EXTENSIONS:
                            continue
                        if skip_done:
                            cached = self.app.library_db.get(p)
                            status, _, _, _ = scan_video_status(p, lang, cached)
                            if status == "DONE":
                                continue
                        video_files.append(p)

        # Deduplicate preserving order
        seen = set()
        unique = []
        for v in video_files:
            if str(v) not in seen:
                seen.add(str(v))
                unique.append(v)

        if not unique:
            self.scan_status.configure(text="No files to process (all DONE?).")
            return

        self.scan_status.configure(text=f"Sending {len(unique)} file(s) to processor…")
        self.app._queue_from_library(unique)
        self.destroy()


# ─── Entry point ──────────────────────────────────────────────────────────────
if __name__ == "__main__":
    app = SubtitleApp()
    app.mainloop()